name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: git clone https://github.com/intel/intel-cmt-cat && cd intel-cmt-cat && make && cd ..
    - name: Build
      run: cargo build --release --verbose
    - name: Run
      run: cargo run --release --verbose
    - name: Run shmem test
      run: cargo test --features=cat-process --release --verbose